# Generated by Django 3.0.6 on 2020-05-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('empid', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=500)),
                ('dob', models.DateTimeField()),
                ('mobile', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
    ]
