# Generated by Django 3.0.6 on 2020-05-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
