# Generated by Django 3.0.6 on 2020-05-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_manager_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
